services:
  ## High performance S3 compabitle object storage
  minio:
    image: quay.io/minio/minio
    container_name: minio-survey-kerabari
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_SERVER_URL: http://localhost:9000
    volumes:
      - ./var/data/object-storage:/data
    command: server /data --console-address ":9001"

  postgres:
    image: postgis/postgis
    container_name: ${POSTGRES_HOSTNAME}-kerabari
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ${POSTGRES_DATA_DIRECTORY}:/var/lib/postgresql/data

  cache:
    image: redis:latest
    container_name: redis-survey-kerabari
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - ./var/data/cache:/data
